# -*- coding: utf-8 -*-
"""faturamento_CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iebr6AYeCyLWuYyRQgsqpd4d5ycXzpPH
"""

import glob
import pandas as pd
from google.colab import files

"""# Instruções

-Primeiro clique em Runtime no menu superior e clique em reset all runtimes -> yes

-Depois que a maquina reiniciar, clique em Runtime novamente e restart and run all -> yes

- na caixa abaixo surgirá um botão escrito "Escolher arquivos, quando ele aparecer, clique e selecione todos os CSVs  que desea fazer o faturamento.
-Espere subir todos e o resultado estará no último bloco, uma planilha com os nomes e IDs não repetidos de todos os arquivos.

Autor: Gustavo Fernandes
"""

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import io

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f, sep=';') for f in all_filenames ])

combined_csv = combined_csv.drop(columns="movimento")
combined_csv = combined_csv.drop(columns="datacriacao")
combined_csv = combined_csv.drop(columns="criadopor")
combined_csv = combined_csv.drop(columns="provider")
combined_csv = combined_csv.drop(columns="sequencialcanal")
combined_csv = combined_csv.drop(columns="totalcanais")
combined_csv = combined_csv.drop(columns="totaldisparo")

combined_csv = combined_csv.drop_duplicates()

combined_csv

from google.colab import files

combined_csv.to_csv('faturamento_CSV.csv')
files.download('faturamento_CSV.csv')